### ISSUE TITLE
class wefe.WordEmbeddingModel with gensim.models.keyedvectors.FastTextKeyedVectors

### ISSUE THREAD

**Issue by elaisa91** [dccuchile/wefe#1]
I'm using WEFE to calculate WEAT with word embeddings and I've observed that WordEmbbeddingModel only works with gensim.models.keyedvectors.Word2VecKeyedVectors. Is that true?

I have some embeddings calculated with Facebook original Fasttext module. Can I use WEFE with them?

Thanks,
Elisabetta.

**Comment by pabloBad** [comment]
Hello @elaisa91 

> I'm using WEFE to calculate WEAT with word embeddings and I've observed that WordEmbbeddingModel only works with gensim.models.keyedvectors.Word2VecKeyedVectors. Is that true?

Unfortunately, loading the models using Word2VecKeyedVectors is currently the only way to run a bias measurement.
During this weekend I could probably improve this limitation to include FastTextKeyedVectors and maybe some other models. 

Best Regards,
Pablo.

**Comment by pabloBad** [comment]
Hello @elaisa91 ,

I just uploaded a new version that allows the use of FastTextKeyedVectors and any object that extends BaseKeyedVectors.


Best Regards,
Pablo.

**Comment by elaisa91** [comment]
Hi @pabloBad ,
thank you very much for your work! 

Best Regards,
Elisabetta.
