### ISSUE TITLE
WEAT p-value is nan

### ISSUE THREAD

**Issue by raffaem** [dccuchile/wefe#15]
Hello,

the WEAT p-value is always nan. 

This happened for two different models I have tried.

Is it normal?

**Comment by pbadillatorrealba** [comment]
Hello @raffaem ,

I'm pretty sure it shouldn't happen.

Could you send me a little more context, like the code you are trying to run?

Best regards, 
Pablo.

**Comment by raffaem** [comment]
@pbadillatorrealba 

The code is just on the line of:

```
weat = WEAT()
wefemodel = WordEmbeddingModel(wv, model_name)
query = Query(target_sets_2, attribute_sets_2, target_sets_names, attribute_sets_names)
result_weat = weat.run_query(query, wefemodel)
```

I now know that if some target words or some attribute words are not present in the word embedding, everything will be `nan`: the `weat`, the `effect_size` and the `p_value` will all be `nan`.

But I now made sure that every target and attribute word is present in the word embedding: the weat and effect_size seems ok, but the p-value remains `nan`.

**Comment by raffaem** [comment]
May it be due to the fact that the two target sets don't have the same size, or that the two attribute sets don't have the same size?

**Comment by raffaem** [comment]
Forget it, I just didn't set `compute_p_value=True`
