### ISSUE TITLE
ImportError: cannot import name 'Literal' from 'typing' in Python 3.7

### ISSUE THREAD

**Issue by soft-nougat** [dccuchile/wefe#20]
Hello!

I have an error running WEFE in Python version < 3.8 due to the fact metrics/WEAT.py calls Literal from typing:

**"/home/appuser/venv/lib/python3.7/site-packages/wefe/metrics/WEAT.py", line 2, in <module>
from typing import Any, Dict, List, Literal, Set, Tuple, Union
ImportError: cannot import name 'Literal' from 'typing'**

This is a known issue for typing, see [here](https://stackoverflow.com/questions/61206437/importerror-cannot-import-name-literal-from-typing?noredirect=1&lq=1).

I would suggest a quick adjustment to WEAT.py, line 2:

try:
    from typing import Literal
except ImportError:
    from typing_extensions import Literal

Please let me know if feasible.

Thanks,
Tia

**Comment by pbadillatorrealba** [comment]
Hi @soft-nougat ,

Thank you for remembering this mistake.
I have just released a new version that fixes this bug and adds a new (contributed) metric.

To update WEFE with pip:

```bash
 pip install -U wefe
```

To update with conda: 

```bash
conda install -c pbadilla wefe 
```

I hope you find this fix useful!
Pablo.
