### ISSUE TITLE
How to reproduce table 1 as in the paper?

### ISSUE THREAD

**Issue by liaocs2008** [dccuchile/wefe#23]
Hello WEFE developers,

I am trying to reproduce your paper results. It looks to me the best reference is your [WEFE-ranking](https://github.com/dccuchile/wefe/blob/master/examples/WEFE_rankings.ipynb) notebook example. Obviously, the notebook can't run directly, with runtime errors as in [this issue](https://github.com/dccuchile/wefe/issues/18). I can fix the syntax problem, but detailed experiment settings are unknown. 

Other errors can show up like:
```
Exception: After dividing the datset using stratified train_test_split, the attribute 0 has 0 training examples.
...
Exception: Error during executing the query: Christianity terms and Islam terms wrt Conservative and Terrorism on the model: word2vec-google-news-300
```

Can you provide a complete notebook simply for reproducing your paper table 1? 

Thanks a lot!

**Comment by liaocs2008** [comment]
I am able to get following results, which seems not match with table 1:




model  | WEAT: Ethnicity average of abs values score | WEAT EZ: Ethnicity average of abs values score | RND: Ethnicity average of abs values score | RNSB: Ethnicity average of abs values score
| -- | -- | -- | -- | --
fasttext-300| 0.162046 | 0.448302 | 0.058224 | 0.035286
glove-giga-300 | 0.415509 | 0.944148 | 0.265921 | 0.119427
conceptnet-19-08 | 0.120199 | 0.441961 | 0.029400 | 0.043845

**Comment by pbadillatorrealba** [comment]
Hi @liaocs2008 

Sorry for the delay in responding.

The framework has changed quite a bit since we built this notebook and unfortunately it was outdated without us noticing it.
During this weekend I will try to update the notebook with the new changes.

I will let you know as soon as I have it ready!

Pablo.

**Comment by liaocs2008** [comment]
Thank you Pablo! This is very helpful!

Just to confirm, values for columns "WEAT" and "WEAT ES" in your updated notebook look switched when compared with the paper.  This is a simple paper formatting problem right?

**Comment by pbadillatorrealba** [comment]
That's right, 

There was a problem in the transcription of the results to the paper and we put them in reverse. 
The tables that appear in the updated notebooks are the correct tables!
