### ISSUE TITLE
Issue with RIPA metric

### ISSUE THREAD

**Issue by h4c5** [dccuchile/wefe#41]
Hi,

I tried to compute RIPA with a single base pair but I get only nan : 

```python
emb_model = WordEmbeddingModel(model)

query = Query(
    target_sets=[["he"], ["she"]],
    attribute_sets=[["doctor", "nurse"]],
    target_sets_names=["male", "female"],
    attribute_sets_names=["profession"],
)

metric = metrics.RIPA()
metric.run_query(gender_query, emb_model, lost_vocabulary_threshold=1.0)

#{'query_name': 'male and female wrt profession',
# 'result': nan,
# 'ripa': nan,
# 'word_values': {'doctor': {'mean': nan, 'std': nan},
#  'nurse': {'mean': nan, 'std': nan}}}
```

I think this comes from [`wefe/metrics/RIPA.py` line 115](https://github.com/dccuchile/wefe/blob/master/wefe/metrics/RIPA.py#L115) :

```python
# calculating the ripa score for each attribute word with each target pair
for word in range(len(attribute_embeddings_0)):
    ripa_scores[attributes[word]] = []
    for index in range(target_length - 1): # <- Should it be range(target_length) instead ?
        bvec = self._b_vec(
            target_embeddings_0[index], target_embeddings_1[index]
        )
        score = self._ripa_calc(attribute_embeddings_0[word], bvec)
        ripa_scores[attributes[word]].append(score)
```

Is there a reason why the last element is not used ?

**Comment by pbadillatorrealba** [comment]
Hi @h4c5 ,

As far as I can see in the original sources of the metric, there is no reason for a pair of targets to be removed, thus showing an implementation error.

Thanks for the PR with the correction :)
I'll check it and let you know if anything is missing or wrong.

**Comment by pbadillatorrealba** [comment]
All tests worked fine, I accepted the pull request.
The modification will be released in the next patch, hopefully during this week.

Thank you!

**Comment by h4c5** [comment]
Thank you for your work 🙂
