### ISSUE TITLE
Missing WEAT words

### ISSUE THREAD

**Issue by kato8966** [dccuchile/wefe#52]
There are two versions of `unpleasant_5` words in the original WEAT paper. One of them is used in WEAT 1, and the other is used in WEAT 3. (For example, the former includes "prison," while the latter does not.) However, `wefe/datasets/data/WEAT.json` has only the former.

I fixed the problem by renaming `unpleasant_5` to `unpleasant_5a` and adding `unpleasant_5b` (This is the fix branch. https://github.com/kato8966/wefe/tree/fix-weat-words), but this breaks backward compatibility.

Should I proceed and make a PR, or should I try a different approach?

**Comment by pbadillatorrealba** [comment]
Hi @kato8966 ,

Thanks for noticing it and trying to correct it!
Yes, make a pull request to develop and we will evaluate it.
Most likely we will have to change the experiments notebook.

**Comment by kato8966** [comment]
Sorry, but I'm currently busy and don't have enough time to fix all the problems caused by this compatibility-breaking change. What do you think I should do?

**Comment by pbadillatorrealba** [comment]
No problem :)
Just upload the patch with the words and I will correct the compatibility issues later.

**Comment by felipebravom** [comment]
Solved
