### ISSUE TITLE
Support gensim 4

### ISSUE THREAD

**Issue by raffaem** [dccuchile/wefe#9]
Following #7, will this library support the upcoming gensim 4?

**Comment by pabloBad** [comment]
Hello @raffaem, 

A few moments ago I made a deploy of a new version of the library. 
It includes by default compatibility with gensim 3.8.9 and gensim 4.

Tell me if there is any problem with this feature.

Best regards,
Pablo.

**Comment by Ali08011988** [comment]
solve  this error ? 
AttributeError                            Traceback (most recent call last)
Cell In[20], line 1
----> 1 ldamallet_45 = gensim.models.wrappers.LdaMallet(mallet_path, corpus=corpus, num_topics=45, id2word=id2word, alpha= 5.0, random_seed = 750)
      2 pprint(ldamallet_45.print_topics(num_words=10, num_topics= 45))

AttributeError: module 'gensim.models' has no attribute 'wrappers'
